# Generated by Django 5.2.15 on 2026-06-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField()),
                ('attempts_used', models.IntegerField()),
                ('marks_scored', models.FloatField()),
            ],
        ),
    ]
