# Generated by Django 5.2.15 on 2026-06-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='correct_answer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='user_answer',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
