# Generated by Django 5.2.4 on 2025-07-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=10)),
                ('sutime', models.DateField()),
            ],
        ),
    ]
