# Generated by Django 5.2.4 on 2025-07-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0002_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='sub',
        ),
    ]
