# Generated by Django 5.2.4 on 2025-07-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0003_student_2_delete_sub'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student_2',
            new_name='MyUserLogin',
        ),
    ]
