# Generated by Django 5.2.4 on 2025-07-26 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0004_rename_student_2_myuserlogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuserlogin',
            old_name='name',
            new_name='username',
        ),
    ]
